<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IS54" failures="1" tests="3" name="TestA" time="0.41" errors="0" timestamp="6 Nov 2018 17:21:50 GMT">
  <testcase classname="com.datadriven.frame.testcases.DummyTestA" name="testA1" time="0.021">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.datadriven.frame.testcases.DummyTestA.testA1(DummyTestA.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testA1 -->
  <testcase classname="com.datadriven.frame.testcases.DummyTestA" name="testA2" time="0.0">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase classname="com.datadriven.frame.testcases.DummyTestA" name="testA3" time="0.0">
    <skipped/>
  </testcase> <!-- testA3 -->
</testsuite> <!-- TestA -->
