<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IS54" failures="1" tests="1" name="TestB" time="48.972" errors="0" timestamp="6 Nov 2018 17:22:38 GMT">
  <testcase classname="com.datadriven.frame.testcases.DummyTestB" name="testB" time="47.427">
    <failure type="java.lang.AssertionError" message="Test Failed">
      <![CDATA[java.lang.AssertionError: Test Failed
	at com.datadriven.frame.base.BaseTest.reportFailure(BaseTest.java:218)
	at com.datadriven.frame.testcases.DummyTestB.testB(DummyTestB.java:105)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
</testsuite> <!-- TestB -->
